#+TITLE: Git

* Table of Contents                                                :TOC_1_gh:
 - [[#resolve-conflicts][Resolve conflicts]]
 - [[#purge-files-including-their-histories][Purge files including their histories]]
 - [[#branch][branch]]
 - [[#flow][flow]]
 - [[#list-tree][list-tree]]
 - [[#log][log]]
 - [[#tag][tag]]

* Resolve conflicts
- https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/
- https://backlogtool.com/git-guide/en/stepup/stepup2_8.html

#+BEGIN_EXAMPLE
  If you have questions, please
  <<<<<<< HEAD
  open an issue
  =======
  ask your question in IRC.
  >>>>>>> branch-a
#+END_EXAMPLE

Fix the conflict like this:
#+BEGIN_EXAMPLE
  If you have questions, please open an issue or ask in our IRC channel if it's more urgent
#+END_EXAMPLE

Stage it:
#+BEGIN_SRC shell
  $ git add guide.md
#+END_SRC

** Commit when merging
#+BEGIN_SRC shell
  $ git commit -m "Resolved merge conflict"
#+END_SRC

** Don't commit, just rebase --continue when rebasing
#+BEGIN_SRC shell
  $ git rebase --continue
#+END_SRC

* Purge files including their histories
- https://help.github.com/articles/removing-sensitive-data-from-a-repository/

** BFG Repo-Cleaner
- https://rtyley.github.io/bfg-repo-cleaner/

#+BEGIN_SRC shell
git clone --mirror git@github.com:yeonghoey/yeonghoey.git
java -jar ~/.local/bin/bfg.jar --strip-blobs-bigger-than 1M yeonghoey.git
cd yeonghoey.git
git reflog expire --expire=now --all && git gc --prune=now --aggressive
git push
#+END_SRC
* branch
- http://railsware.com/blog/2014/08/11/git-housekeeping-tutorial-clean-up-outdated-branches-in-local-and-remote-repositories/

** Cleanup branches
#+BEGIN_SRC shell
  $ git checkout master

  # Show targets before deleting
  $ git branch --merged
  $ git branch -d old-merged-feature

  $ git branch --no-merged
  $ git branch -D old-abandoned-feature
#+END_SRC

#+BEGIN_SRC shell
  # Delete all merged, except master
  $ git branch --merged | grep -v master | xargs git branch -d
#+END_SRC

** Cleanup remote branch references
#+BEGIN_SRC shell
  # Show targets
  $ git branch --remotes
  $ git remote prune origin
#+END_SRC

#+BEGIN_SRC shell
  # prune when fetching
  $ git fetch --prune
#+END_SRC

* flow
- http://danielkummer.github.io/git-flow-cheatsheet/index.html

** git flow release finish
Make sure the local ~develop~ and ~master~ branches are fresh.
When trigger ~finish~, the merge flow is following:
1. merges ~release/something~  into ~master~
2. creates a tag on the ~master~ commit.
3. merges ~master~ into ~develop~

** When it comes to code review
- http://softwareengineering.stackexchange.com/questions/187723/code-review-with-git-flow-and-github

~git flow feature finish~ just merges into develop without code review.
To work around this, just don't use ~finish~ but make a pull request
and delete the branch manually after it merged.

* list-tree
#+BEGIN_SRC shell
  # lists all of the already committed files being tracked by your git repo.
  $ git ls-tree --full-tree -r HEAD
#+END_SRC

* log
** Find deleted files
- http://stackoverflow.com/questions/7203515/git-how-to-search-for-a-deleted-file-in-the-project-commit-history
#+BEGIN_SRC shell
  git log --all --full-history -- **/thefile.*
  git log --all --full-history -- <path-to-file>  # if you know the exact path

  # Reveal the content
  git show <SHA> -- <path-to-file>

  # Note '^', checking out from the previous commit.
  # There won't exist the file in <SHA> because it has been deleted.
  git checkout <SHA>^ -- <path-to-file>
#+END_SRC
* tag
** Prune local git tags that don't exist on remote
- https://demisx.github.io/git/2014/11/02/git-prune-local-tags-dont-exist-remote.html

#+BEGIN_SRC shell
  $ git tag -l | xargs git tag -d # remove all local tags
  $ git fetch -t                  # fetch remote tags
#+END_SRC
