#+TITLE: Linux

* Table of Contents                                                :TOC_2_gh:
 - [[#mounting-a-volume][Mounting a Volume]]
   - [[#basic-workflow][Basic Workflow]]
   - [[#lostfound][lost+found]]
 - [[#ubuntu-specific-features][Ubuntu Specific Features]]
   - [[#apt][apt]]

* Mounting a Volume
- http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-using-volumes.html

** Basic Workflow
#+BEGIN_SRC shell
  # view your available disk devices and their mount points 
  $ lsblk
  NAME  MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
  xvdf  202:80   0  100G  0 disk
  xvda1 202:1    0    8G  0 disk /
#+END_SRC

#+BEGIN_SRC shell
  $ sudo file -s /dev/xvda1
  /dev/xvda1: Linux rev 1.0 ext4 filesystem data, UUID=1701d228-e1bd-4094-a14c-8c64d6819362, ...

  # no file system
  $ sudo file -s /dev/xvdf
  /dev/xvdf: data
#+END_SRC

#+BEGIN_SRC shell
  $ sudo mkfs -t ext4 /dev/xvdf

  $ sudo mkdir /my/path
  $ sudo mount /dev/xvdf /my/path
#+END_SRC

#+BEGIN_SRC shell
  # Mount the volume permanently
  $ sudo cp /etc/fstab /etc/fstab.orig  # backup

  # /etc/fstab : columns are separated with '\t'
  # ------------------------------------------------------------------------------
  # Use UUID because /dev/xvdf may change
  # - check UUID from the output of file -s /dev/xvdf
  # SEE: $ man fstab
  # - 0 stands for (not dumping, default)
  # - 2 stands for (other than root volume)
  /dev/xvda1  (...)
  UUID=de9a1ccd-a2dd-44f1-8be8-2d4275cb85a3  /my/path  ext4  defaults,nofail  0  2
  # ------------------------------------------------------------------------------

  # mount with /etc/fstab manually
  $ sudo mount -a
#+END_SRC

** lost+found
- http://unix.stackexchange.com/questions/18154/what-is-the-purpose-of-the-lostfound-folder-in-linux-and-unix

#+BEGIN_QUOTE
The thing is, the file had a name and location once, but that information is no longer available.
So fsck deposits the file in a specific directory, called lost+found
#+END_QUOTE

#+BEGIN_QUOTE
Files that appear in lost+found are typically files that were already unlinked (i.e. their name had been erased)
but still opened by some process (so the data wasn't erased yet)when the system halted suddenly (kernel panic or power failure).
If that's all that happened, these files were slated for deletion anyway, you don't need to care about them.
#+END_QUOTE

#+BEGIN_QUOTE
On many filesystems, the lost+found directory is a bit special
because it preallocates a bit of space for fsck to deposit files there. (...)
If you accidentally delete lost+found, don't re-create it with mkdir, use mklost+found if available.
#+END_QUOTE

* Ubuntu Specific Features
** apt
*** Failing apt-get update

- Check files in:
  #+BEGIN_EXAMPLE
    /etc/apt/sources.list
    /etc/apt/sources.list.d/*.list
  #+END_EXAMPLE

***  Install java8
- http://tecadmin.net/install-oracle-java-8-jdk-8-ubuntu-via-ppa/
 
#+BEGIN_SRC shell
  sudo add-apt-repository ppa:webupd8team/java
  sudo apt-get update
  sudo apt-get install oracle-java8-installer

  java -version
  sudo apt-get install oracle-java8-set-default

  sudo update-alternatives --config java
#+END_SRC
