#+TITLE: Org

* Table of Contents                                                :TOC_1_GH:
 - [[#document-meta][Document Meta]]
 - [[#markup][Markup]]
 - [[#easy-templates][Easy Templates]]
 - [[#babel][Babel]]
 - [[#agenda][Agenda]]

* Document Meta
- http://orgmode.org/manual/Structural-markup-elements.html

#+BEGIN_EXAMPLE
  ,#+TITLE: This is the title of the document
  ,#+OPTIONS: toc:2    (only inlcude two levels in TOC)
  ,#+OPTIONS: toc:nil  (no default TOC at all)

  ,#+TOC: headlines 2        (insert TOC here)
  ,#+TOC: headlines 1 local  (insert local TOC, direct children only)
  ,#+TOC: listings           (build a list of listings)
  ,#+TOC: tables             (build a list of tables)

  ,#+INCLUDE: "~/.emacs" src emacs-lisp
  ,#+INCLUDE: "~/my-book/chapter2.org" :minlevel 1
  ,#+INCLUDE: "~/.emacs" :lines "5-10"                 [5 to 10)
  ,#+INCLUDE: "~/.emacs" :lines "-10"                  [1 to 10)
  ,#+INCLUDE: "~/.emacs" :lines "10-"                  [10 to EOF)
  ,#+INCLUDE: "./paper.org::#theory" :only-contents t  (custom-id)
  ,#+INCLUDE: "./paper.org::mytable"                   (named element)
  ,#+INCLUDE: "./paper.org::*conclusion" :lines 1-20   (headline named 'conclusion')

  ,#+MACRO: name   replacement text $1, $2 are arguments
  {{{name(arg1, arg2)}}}
  {{{title}}}
  {{{author}}}
  {{{email}}}
  {{{date}}}
  {{{date(FORMAT)}}}
  {{{time(FORMAT)}}}
  {{{modification-time(FORMAT, VC)}}}
  {{{input-file}}}
  {{{property(PROPERTY-NAME)}}}
  {{{property(PROPERTY-NAME,SEARCH-OPTION)}}}

  ,* Goldberg Variations
  :PROPERTIES:
  :Title:     Goldberg Variations
  :Composer:  J.S. Bach
  :Artist:    Glen Gould
  :Publisher: Deutsche Grammophon
  :NDisks:    1
  :END:
#+END_EXAMPLE

** Omitting #+TITLE
- http://orgmode.org/manual/Document-title.html#Document-title
#+BEGIN_QUOTE
If you are exporting only a subtree,
*its heading will become the title of the document.
If the subtree has a property EXPORT_TITLE, that will take precedence.
#+END_QUOTE

* Markup
- http://orgmode.org/manual/Markup.html#Markup
- http://ergoemacs.org/emacs/emacs_org_markup.html
- http://orgmode.org/manual/External-links.html#External-links

#+BEGIN_EXAMPLE
    ,* 1st level heading
    ,** this is 2nd level heading
    ,*** this is 3rd level heading

    ,*bold*
    /italic/
    _underlined_
    =verbatim=
    ~code~
    +strike-through+
    X_{subscript}, X^{superscript}

    Hello, \\  (enforce line break within a paragraph)
    World.

    - 1st item
    ,* another item
    + and 3rd item :: this is a description

    1. 1st item
    2) another item

    20. [@20] Test
    21. xargs
    22. bcadf

    [[http://example.com/]]
    [[http://example.com/][description]]

    -----
    (a horizontal rule, 5 or more only dashes)

    ,#+BEGIN_EXAMPLE
      verbatime example
    ,#+END_EXAMPLE

    ,#+BEGIN_SOURCE python
      print 'hello, world!'
    ,#+END+SOURCE

    : a single line example
      : can be indented
    (start the example lines with a colon followed by a space.)
#+END_EXAMPLE

** code(~~) vs verbatim(==)
- http://stackoverflow.com/questions/18991981/difference-between-code-and-verbatim-in-org-mode
- There are some differences in ~Latex~ related things, but *identical others*.

** Can't stylize part of a word
- http://stackoverflow.com/questions/1218238/how-to-make-part-of-a-word-bold-in-org-mode

#+BEGIN_QUOTE
Org-mode relies on heuristics to distinguish emphasis from
normal text, and one of the most important parts of this
heuristics method is *assuming that emphasis is on whole words*,
delimited by whitespace or punctuation.
#+END_QUOTE

* Easy Templates
- http://orgmode.org/manual/Easy-Templates.html

#+BEGIN_EXAMPLE
  s #+BEGIN_SRC ... #+END_SRC
  e #+BEGIN_EXAMPLE ... #+END_EXAMPLE
  q #+BEGIN_QUOTE ... #+END_QUOTE
  v #+BEGIN_VERSE ... #+END_VERSE
  c #+BEGIN_CENTER ... #+END_CENTER
  l #+BEGIN_LaTeX ... #+END_LaTeX
  L #+LaTeX:
  h #+BEGIN_HTML ... #+END_HTML
  H #+HTML:
  a #+BEGIN_ASCII ... #+END_ASCII
  A #+ASCII:
  i #+INDEX: line
  I #+INCLUDE: lin
#+END_EXAMPLE

* Babel
- http://orgmode.org/worg/org-contrib/babel/languages.html
- http://orgmode.org/manual/Structure-of-code-blocks.html
 
** Basics
#+BEGIN_SRC org
  ,#+NAME: <name>
  ,#+BEGIN_SRC <language> <switches> <header arguments>
     <body>
  ,#+END_SRC

  ,#+BEGIN_SRC emacs-lisp
  ,#+BEGIN_SRC emacs-lisp -n 20  ;; Show line numbers starting from 20
  ,#+BEGIN_SRC emacs-lisp +n 20  ;; Show line numbers ending with 20
#+END_SRC

** Python
#+BEGIN_SRC org
  ,#+BEGIN_SRC python :results output
    print "Hello, world!"
  ,#+END_SRC

  ,#+RESULTS:
  : Hello, world!

  ,#+TBLNAME: data_table
  | a | 1 |
  | b | 2 |
  | c | 3 |

  ,#+BEGIN_SRC python :var val=1 :var data=data_table
    return data[val]
  ,#+END_SRC

  ,#+RESULTS:
  | b | 2 |
#+END_SRC

* Agenda
- http://orgmode.org/manual/Capture-templates.html#Capture-templates
 
#+BEGIN_EXAMPLE
  <2006-11-01 Wed>
  [2006-11-01 Wed]  # inactive timestamps, they do not trigger an entry to show up in the agenda.
#+END_EXAMPLE
